[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wid = "9nemP4rKsEh7nRSLisCu5VGeHXC9gdrtmgWvC1WLz1Tb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/wid.ts"

[test]
startup_wait = 3000
