[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
id_gateway = "4nRiMFwTjJaR8kPNdw7y9f3vSCWGik3PVx7a1cTvi5uf"
id_registry = "J4gHEDBT7DAQy9eExU2DHYNX55x6VqtbfCrvVAdMPLv1"
signed_key_request_validator = "r4j2QWkASQPuh8yhsJ1bLBiM6k5shGoUWANUWG2inwS"
signer_gateway = "CyXDSVbU99MksfgPktKfk7e3wcSy4JrDMWDTdd8k6ZKB"
signer_registry = "GzHMQ5gBpzw5LR8pjGLQHqJWZiq7trJ5T73PYp2ESzqQ"
storage_registry = "BbMwSGQAArCGSmk25TDBcP3jSyMK2Mu1TKZQeiNXF52x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/wid.ts"

[test]
startup_wait = 3000
shutdown_wait = 2000
upgradeable = false
