[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
id_gateway = "FEW1NtVZjD5u3ChatB9gCBKyvnbFibP7pn8ed81UWYqZ"
id_registry = "CGjicJKZE9tYBxMup4nhmrzfbonb6uNcYUFx5KV8U7n5"
signer_gateway = "BWPppCHLqGTWZa8AmD9kFNxa9qXxDu9EfgWjp7sWSsD9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/wid.ts"

[test]
startup_wait = 3000
shutdown_wait = 2000
upgradeable = false
